### ISSUE TITLE
Can grid be applied?

### ISSUE THREAD

**Issue by codiejay** [JABedford/Dev-Folio#1]
Hello @JABedford , hope you great!  I noticed you didn't apply CSS grid to this (Please pardon me if I'm seeing wrong) So i wanted to know if there was any reason why you didn't use it? or is it because it only 4 boxes? Have a great day  and I love this!

**Comment by jameesy** [comment]
Hi James,

I didn't use Grid in this instance because I wanted to avoid using concepts that beginners might not have learned yet. 

In this instance Grid certainly would be a good option! As well as flex :) 
I plan on releasing other templates so might do a grid template at some point.


EDIT:
This could be quite a good little project for someone if they want to transform the current template and then merge it back, where I can add it to the main repo.
